Parameters:
    BucketName:
        Type: String
Resources:
    WebBucket:
        Type: AWS::S3::Bucket
        Properties:
            AccessControl: PublicRead
            BucketName: !Ref BucketName
            PublicAccessBlockConfiguration:
                BlockPublicAcls: false
                BlockPublicPolicy: false
                IgnorePublicAcls: false
                RestrictPublicBuckets: false
    CloudFrontOriginIdentity:
        Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
        Properties:
            CloudFrontOriginAccessIdentityConfig:
                Comment: 'origin identity'
    BucketPolicy:
        Type: AWS::S3::BucketPolicy
        Properties:
            Bucket: !Ref WebBucket
            PolicyDocument:
                Version: '2012-10-17'
                Id: 'PolicyForCloudFront'
                Statement:
                    - Effect: Allow
                      Sid: '1'
                      Principal:
                          AWS: !Sub 'arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity ${CloudFrontOriginIdentity}'
                      Action: 's3:GetObject'
                      Resource: !Sub 'arn:aws:s3:::${WebBucket}/*'
    cachePolicy:
        Type: AWS::CloudFront::CachePolicy
        Properties:
            CachePolicyConfig:
                Name: !Sub '${BucketName}CachePolicy'
                DefaultTTL: 86400
                MaxTTL: 31536000
                MinTTL: 1
                ParametersInCacheKeyAndForwardedToOrigin:
                    CookiesConfig:
                        CookieBehavior: none
                    EnableAcceptEncodingGzip: true
                    HeadersConfig:
                        HeaderBehavior: none
                    QueryStringsConfig:
                        QueryStringBehavior: none
    publicDistribution:
        Type: AWS::CloudFront::Distribution
        Properties:
            DistributionConfig:
                Origins:
                    - DomainName: !Sub '${BucketName}.s3.us-east-1.amazonaws.com'
                      Id: MyCustomOriginId
                      CustomOriginConfig:
                          OriginProtocolPolicy: https-only
                Enabled: 'true'
                IPV6Enabled: 'true'
                Comment: Some comment
                CacheBehaviors:
                    - CachePolicyId: !Ref cachePolicy
                      PathPattern: /*
                      TargetOriginId: MyCustomOriginId
                      ViewerProtocolPolicy: allow-all
                DefaultCacheBehavior:
                    CachePolicyId: !Ref cachePolicy
                    AllowedMethods:
                        - GET
                        - HEAD
                    TargetOriginId: MyCustomOriginId
                    ViewerProtocolPolicy: allow-all
        DependsOn:
            - WebBucket