AWSTemplateFormatVersion: '2010-09-09'

Parameters:
    BucketName:
        Type: String
    RegionName: 
        Type: String

Resources:
    s3Bucket:
        Type: AWS::S3::Bucket
        Properties:
            AccessControl: PublicRead
            BucketName: !Ref BucketName
            DeletionPolicy: Retain
            PublicAccessBlockConfiguration:
                BlockPublicAcls: true
                BlockPublicPolicy: true
                IgnorePublicAcls: true
                RestrictPublicBuckets: true
            WebsiteConfiguration:
                IndexDocument: index.html
                ErrorDocument: error.html
            
    CloudFrontOriginIdentity:
        Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
        Properties:
            CloudFrontOriginAccessIdentityConfig:
                Comment: 'Origin Identity Creation'

    BucketPolicy:
        Type: AWS::S3::BucketPolicy
        Properties:
            Bucket: !Ref s3Bucket
            PolicyDocument:
                Version: '2012-10-17'
                Id: 'PolicyForCloudFront'
                Statement:
                    - Effect: Allow
                      Sid: '1'
                      Principal:
                          AWS: !Sub 'arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity ${CloudFrontOriginIdentity}'
                      Action: 's3:GetObject'
                      Resource: !Sub 'arn:aws:s3:::${s3Bucket}/*'

    cachePolicy:
        Type: AWS::CloudFront::CachePolicy
        Properties:
            CachePolicyConfig:
                Name: !Sub '${BucketName}CachePolicy'
                DefaultTTL: 86400
                MaxTTL: 31536000
                MinTTL: 1
                ParametersInCacheKeyAndForwardedToOrigin:
                    CookiesConfig:
                        CookieBehavior: none
                    EnableAcceptEncodingGzip: true
                    HeadersConfig:
                        HeaderBehavior: none
                    QueryStringsConfig:
                        QueryStringBehavior: none

    publicDistribution:
        Type: AWS::CloudFront::Distribution
        Properties:
            DistributionConfig:
                Origins:
                    - DomainName: !Sub '${BucketName}.s3.${RegionName}.amazonaws.com'
                      Id: MyCustomOriginId
                      S3OriginConfig:
                          OriginAccessIdentity: !Sub 'origin-access-identity/cloudfront/${CloudFrontOriginIdentity}'
                Enabled: 'true'
                Comment: Distribution from CloudFront to S3 Bucket
                CacheBehaviors:
                    - CachePolicyId: !Ref cachePolicy
                      PathPattern: /*
                      TargetOriginId: MyCustomOriginId
                      ViewerProtocolPolicy: allow-all
                DefaultCacheBehavior:
                    CachePolicyId: !Ref cachePolicy
                    AllowedMethods:
                        - GET
                        - HEAD
                    TargetOriginId: MyCustomOriginId
                    ViewerProtocolPolicy: allow-all

        DependsOn:
            - s3Bucket